CT_MEAN_STD: [0., 1.]
XRAY1_MEAN_STD: [0., 1.]
XRAY2_MEAN_STD: [0., 1.0]
XRAY1_MIN_MAX: [0, 255]
XRAY2_MIN_MAX: [0, 255]
CT_MIN_MAX: [0, 2500]

NETWORK:
  input_nc_D: 1
  input_nc_G: 512
  output_nc_G: 1
  no_dropout: True
  n_downsampling: 4
  n_blocks: 1
  ngf: 64

  ndf: 64
  which_model_netG: 'multiview_network_denseUNetFuse_transposed'
  which_model_netD: 'basic3d'
  norm_D: 'instance3d'
  norm_G: 'instance3d'
  ganloss: 'lsgan'
  num_D: 3
  activation_type: 'relu'
  n_out_ChannelsD: 1
  conditional_D: True

  map_input_nc_D: 1
  map_ndf: 64
  map_which_model_netD: 'multi2d'
  map_n_layers_D: 3
  map_norm_D: 'instance'
  map_pool_size: 50
  map_num_D: 3
  map_n_out_ChannelsD: 1

TRAIN:
  print_freq: 10
  save_epoch_freq: 10
  save_latest_freq: 1000
  print_img_freq: 2
  niter: 5
  niter_decay: 5
  beta1: 0.5
  beta2: 0.99
  lr: 0.0002
  batch_size: 1
  weight_decay_if: False

CTGAN:
  Xray1_Direction: 'HDW'
  Xray2_Direction: 'WDH'
  CTOrder: [0, 1, 2, 3, 4]
  CTOrder_Xray1: [0, 1, 3, 2, 4]
  CTOrder_Xray2: [0, 1, 4, 2, 3]
  idt_lambda: 10.
  idt_reduction: 'elementwise_mean'
  idt_weight: 0.
  idt_weight_range: [0., 1.]
  # 'l1' or 'mse'
  idt_loss: 'mse'
  feature_D_lambda: 0.
  map_projection_lambda: 10.
  # 'l1' or 'mse'
  map_projection_loss: 'l1'
  gan_lambda: 0.1
  auxiliary_loss: 'mse'
  auxiliary_lambda: 0.





TD_GAN:
  idt_lambda: 1.
  restruction_loss: 'mse'
  fea_m_lambda: 10.
  map_m_lambda: 0.
  map_m_type: 'l1'
  fea_m_map_lambda: 10.
  discriminator_feature: False
  critic_times: 1

D3_GAN:
  noise_len: 1000
  input_shape: [4,4,4]
  output_shape: [128,128,128]
  encoder_input_shape: [128, 128]
  encoder_input_nc: 1
  encoder_norm: 'instance'
  multi_view: [1,2,3]
  min_max_norm: True
  dblu: [0., 1., 1.]
  encoder_blocks: 3

DATA_AUG:
  select_slice_num: 0
  fine_size: 128
  ct_channel: 128
  xray_channel: 1
  resize_size: 150
